[package]
name = "desktop-tauri-backend"
version = "0.1.0"
edition = "2021"

[workspace]

[features]
default = []
tauri-app = ["dep:tauri"]

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2", optional = true }
